### ISSUE TITLE
Bug: windows 10 `pip install eth-ape` fails building `pyethhash` error: `'alloca.h': No such file or directory`

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape#91]
### Environment information

* `ape` and plugin versions: 

```
`eth_ape-0.1.0a14-py3-none-any.whl`
```

* Python Version: 3.8.3
* OS: Windows 10

### What went wrong?

`PS> pip install eth-ape` errors installing `pyethhash` dependency
`fatal error C1083: Cannot open include file: 'alloca.h': No such file or directory` 

### How can it be fixed?

upstream issue in `pyethhash` https://github.com/ConsenSys/ethjsonrpc/issues/5

**Comment by sabotagebeats** [comment]
also experiencing this in anaconda for windows

**Comment by unparalleled-js** [comment]
Have you tried adding `-D MS_WIN64` to the compile flags in `setup.py`?

Reference:  last comment here https://github.com/ethereum/ethash/issues/87

**Comment by sabotagebeats** [comment]
> Have you tried adding `-D MS_WIN64` to the compile flags in `setup.py`?
> 
> Reference: last comment here [ethereum/ethash#87](https://github.com/ethereum/ethash/issues/87)

No i have not, I think that @lost-theory was working on trying to resolve this as well so may have some helpful inputs

**Comment by lost-theory** [comment]
Yes, I tried that `-D MS_WIN64` flag and it didn't do anything. Here's how I was able to workaround this issue and get Ape to install on Windows 

1. Clone github.com/ethereum/ethash
2. Apply this patch:

```
diff --git a/setup.py b/setup.py
index 18aa20f..fd01603 100755
--- a/setup.py
+++ b/setup.py
@@ -38,7 +38,7 @@ setup(
     author="Matthew Wampler-Doty",
     author_email="matthew.wampler.doty@gmail.com",
     license='GPL',
-    version='0.1.23',
+    version='0.1.27',
     url='https://github.com/ethereum/ethash',
     download_url='https://github.com/ethereum/ethash/tarball/v23',
     description=('Python wrappers for ethash, the ethereum proof of work'
diff --git a/src/libethash/io_win32.c b/src/libethash/io_win32.c
index 34f1aaa..30f819f 100644
--- a/src/libethash/io_win32.c
+++ b/src/libethash/io_win32.c
@@ -89,6 +89,8 @@ bool ethash_get_default_dirname(char* strbuf, size_t buffsize)
 {
 	static const char dir_suffix[] = "Ethash\\";
 	strbuf[0] = '\0';
+	return false;
+	/*
 	if (!SUCCEEDED(SHGetFolderPathA(NULL, CSIDL_LOCAL_APPDATA, NULL, 0, (CHAR*)strbuf))) {
 		return false;
 	}
@@ -97,4 +99,5 @@ bool ethash_get_default_dirname(char* strbuf, size_t buffsize)
 	}
 
 	return ethash_strncat(strbuf, buffsize, dir_suffix, sizeof(dir_suffix));
+	*/
 }
diff --git a/src/libethash/util_win32.c b/src/libethash/util_win32.c
index 268e6db..59693b9 100644
--- a/src/libethash/util_win32.c
+++ b/src/libethash/util_win32.c
@@ -35,4 +35,4 @@ void debugf(char const* str, ...)
 	_vsnprintf_s(buf, sizeof(buf), sizeof(buf), str, args);
 	buf[sizeof(buf)-1] = '\0';
 	OutputDebugStringA(buf);
-}
+}
\ No newline at end of file
diff --git a/src/python/core.c b/src/python/core.c
index c66e03c..e89d40c 100644
--- a/src/python/core.c
+++ b/src/python/core.c
@@ -1,5 +1,5 @@
 #include <Python.h>
-#include <alloca.h>
+#include <malloc.h>
 #include <stdint.h>
 #include <stdlib.h>
 #include <time.h>
diff --git a/test/c/test.cpp b/test/c/test.cpp
index 44e0c38..de5d3aa 100644
--- a/test/c/test.cpp
+++ b/test/c/test.cpp
@@ -296,7 +296,7 @@ BOOST_AUTO_TEST_CASE(test_ethash_get_default_dirname) {
 	// TODO: Improve this test ...
 #ifdef _WIN32
 	char homedir[256];
-	BOOST_REQUIRE(SUCCEEDED(SHGetFolderPathA(NULL, CSIDL_PROFILE, NULL, 0, (CHAR*)homedir)));
+	//BOOST_REQUIRE(SUCCEEDED(SHGetFolderPathA(NULL, CSIDL_PROFILE, NULL, 0, (CHAR*)homedir)));
 	BOOST_REQUIRE(ethash_get_default_dirname(result, 256));
 	std::string res = std::string(homedir) + std::string("\\AppData\\Local\\Ethash\\");
 #else
```

3. Create a venv and run `python setup.py install` for ethash in the venv.
4. Now you can do `pip install eth-ape` or `pip install -e .[dev]` in the ape repo and it'll use the already installed version of pyethash when installing all the dependencies (it's actually `py-evm` which requires `pyethash>=0.1.27,<1.0.0`).

Note that the patch is step 2 may be removing some important code. It's not a real fix, just a workaround I came up with to see if the package would build.

**Comment by lost-theory** [comment]
Very up to date fork of ethash that doesn't seem to support Windows: https://github.com/chfast/ethash

**Comment by lost-theory** [comment]
This is the definitive issue on what's blocking Windows support, with next steps on how to fix the issue and making a new release (if pyethash was still maintained):

https://github.com/ethereum/ethash/pull/107

**Comment by fubuloubu** [comment]
So, one thing that would help here is to remove the `eth-tester` provider defined under `ape_test`, this way we could at least push that to a different plugin where windows support isn't necessary

Otherwise, the trick would be to make some modifications to `py-evm` to make `ethash` optional for only situations where you'd need to validate headers (I don't think a precompile uses this like with `blake2b`)

**Comment by NotPeopling2day** [comment]
No CI support yet this ticket blocked lost-theory in https://github.com/ApeWorX/ape-hardhat/pull/2

**Comment by Nov1kov** [comment]
I installed the APE on Windows, using this workaround to install ethash https://github.com/ethereum/ethash/issues/131

But it still has problems. For example, `ape plugins list` doesn't show anything. Something wrong with pydantic + enums in 
`installed = PluginGroup(plugin_type=PluginType.INSTALLED)`

**Comment by antazoey** [comment]
> But it still has problems. For example, `ape plugins list` doesn't show anything. Something wrong with pydantic + enums in `installed = PluginGroup(plugin_type=PluginType.INSTALLED)`

We think we fixed the weird Enum problem here: https://github.com/ApeWorX/ape/pull/1745

**Comment by Nov1kov** [comment]
> > But it still has problems. For example, `ape plugins list` doesn't show anything. Something wrong with pydantic + enums in `installed = PluginGroup(plugin_type=PluginType.INSTALLED)`
> 
> We think we fixed the weird Enum problem here: #1745

Oh yes, it's quite a coincidence that MR 3 hours ago fixed my issue. I checked the master branch, and it's working! Thank you.

**Comment by antazoey** [comment]
> > > But it still has problems. For example, `ape plugins list` doesn't show anything. Something wrong with pydantic + enums in `installed = PluginGroup(plugin_type=PluginType.INSTALLED)`
> > 
> > 
> > We think we fixed the weird Enum problem here: #1745
> 
> Oh yes, it's quite a coincidence that MR 3 hours ago fixed my issue. I checked the master branch, and it's working! Thank you.

Yes that was odd timing! However, I am pretty happy you found a way to get it working on windows 10 and I would like to both document this and include the `windows-latest` matrix value in CI such that it works.

**Comment by Nov1kov** [comment]
Great! 
To clarify, In my case I tested on winsows 11 + python 3.10 + [custom install ethash](https://github.com/ethereum/ethash/issues/131#issuecomment-1091152227). It's still not easy "pip install" way.

**Comment by antazoey** [comment]
this is no longer an issue - ever since: Windows support isn't 100% there yet, but this specific problem has been resolved since: https://github.com/ethereum/py-evm/pull/2121 and Ape is using later versions of eth dependencies already.

however we are not 100% windows compat yet.
